# Generated by Django 4.0.2 on 2022-06-06 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner_name', models.CharField(max_length=50)),
                ('Owner_Id', models.IntegerField()),
                ('car_model', models.CharField(max_length=200)),
                ('owner_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone_number_assign', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('owner_email', models.EmailField(max_length=254)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('time_done', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Car Registration',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MoneyCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_charges', models.PositiveIntegerField(blank=True, null=True)),
                ('control_charges', models.PositiveIntegerField(blank=True, null=True)),
                ('tax_charges', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Money charges',
            },
        ),
        migrations.CreateModel(
            name='Unregistered_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=50)),
                ('time_done', models.DateTimeField(auto_now_add=True)),
                ('danger', models.BooleanField()),
                ('police', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Unregistered Car',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=50)),
                ('tax_start', models.DateField()),
                ('tax_end', models.DateField()),
                ('time_done', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_plate.car_registration')),
            ],
            options={
                'verbose_name_plural': 'Tax',
            },
        ),
        migrations.CreateModel(
            name='Police_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_status', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('denied', 'denied')], max_length=50)),
                ('time_done', models.DateTimeField(auto_now_add=True)),
                ('police', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Police Request',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=50)),
                ('insurance_duration_start', models.DateField()),
                ('insurance_duration_end', models.DateField()),
                ('time_done', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_plate.car_registration')),
            ],
            options={
                'verbose_name_plural': 'Insurance',
            },
        ),
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummy_name', models.CharField(default='Dummy', max_length=20)),
                ('time_done', models.DateTimeField(auto_now_add=True)),
                ('police', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dummy',
            },
        ),
        migrations.CreateModel(
            name='Charged_car_official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_charged_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('tax_charged_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('control_charged_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('insurance_tole_expire', models.DateField(blank=True, null=True)),
                ('control_tole_expire', models.DateField(blank=True, null=True)),
                ('tax_tole_expire', models.DateField(blank=True, null=True)),
                ('time_done', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_plate.car_registration')),
                ('police', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Charged Car Official',
            },
        ),
        migrations.CreateModel(
            name='Charged_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_charged', models.PositiveIntegerField(default=0)),
                ('tax_charged', models.PositiveIntegerField(default=0)),
                ('control_charged', models.PositiveIntegerField(default=0)),
                ('insurance_ban_expire', models.DateField(blank=True, null=True)),
                ('control_ban_expire', models.DateField(blank=True, null=True)),
                ('tax_ban_expire', models.DateField(blank=True, null=True)),
                ('time_done', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_plate.car_registration')),
                ('police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Charged Car',
            },
        ),
        migrations.CreateModel(
            name='Car_Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_name', models.CharField(max_length=50)),
                ('control_start', models.DateField()),
                ('control_end', models.DateField()),
                ('time_done', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_plate.car_registration')),
            ],
            options={
                'verbose_name_plural': 'Car Control',
            },
        ),
        migrations.CreateModel(
            name='Captured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_status', models.BooleanField()),
                ('tax_status', models.BooleanField()),
                ('control_status', models.BooleanField()),
                ('time_done', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_plate.car_registration')),
                ('police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Captured',
                'ordering': ['-time_done'],
            },
        ),
    ]
