# Generated by Django 4.0.2 on 2022-04-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_plate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_registration',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Car Registration'},
        ),
    ]
