# Generated by Django 4.0.2 on 2022-04-22 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_plate', '0002_alter_car_registration_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charged_car_official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_charged_amount', models.PositiveIntegerField(default=0)),
                ('tax_charged_amount', models.PositiveIntegerField(default=0)),
                ('control_charged_amount', models.PositiveIntegerField(default=0)),
                ('insurance_tole_expire', models.DateField()),
                ('control_tole_expire', models.DateField()),
                ('tax_tole_expire', models.DateField()),
                ('time_done', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_plate.car_registration')),
                ('police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Charged Car Official',
            },
        ),
    ]
