# Generated by Django 4.0.2 on 2022-04-22 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_plate', '0003_charged_car_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charged_car_official',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_plate.car_registration'),
        ),
        migrations.AlterField(
            model_name='charged_car_official',
            name='control_charged_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='charged_car_official',
            name='control_tole_expire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charged_car_official',
            name='insurance_charged_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='charged_car_official',
            name='insurance_tole_expire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charged_car_official',
            name='police',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='charged_car_official',
            name='tax_charged_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='charged_car_official',
            name='tax_tole_expire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
