# Generated by Django 4.0.2 on 2022-04-24 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_plate', '0004_alter_charged_car_official_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charged_car',
            name='control_ban_expire',
            field=models.DateField(default=datetime.date(2022, 4, 24)),
        ),
        migrations.AddField(
            model_name='charged_car',
            name='insurance_ban_expire',
            field=models.DateField(default=datetime.date(2022, 4, 24)),
        ),
        migrations.AddField(
            model_name='charged_car',
            name='tax_ban_expire',
            field=models.DateField(default=datetime.date(2022, 4, 24)),
        ),
    ]
