# Generated by Django 4.0.2 on 2022-04-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_plate', '0007_dummy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dummy',
            options={'verbose_name_plural': 'Dummy'},
        ),
    ]
