# Generated by Django 4.0.2 on 2022-04-24 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_plate', '0008_alter_dummy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unregistered_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=50)),
                ('time_done', models.DateTimeField(auto_now_add=True)),
                ('danger', models.BooleanField()),
                ('police', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Unregistered Car',
            },
        ),
    ]
