# Generated by Django 4.0.2 on 2022-04-28 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_plate', '0010_alter_charged_car_control_ban_expire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Police_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_status', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('denied', 'denied')], max_length=50)),
                ('time_done', models.DateTimeField(auto_now_add=True)),
                ('police', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Police Request',
                'ordering': ['-id'],
            },
        ),
    ]
