# Generated by Django 4.0.2 on 2022-05-15 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_plate', '0015_alter_charged_car_control_ban_expire_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captured',
            options={'ordering': ['-time_done'], 'verbose_name_plural': 'Captured'},
        ),
        migrations.AlterField(
            model_name='charged_car',
            name='control_ban_expire',
            field=models.DateField(blank=True, default=datetime.date(2022, 5, 15), null=True),
        ),
        migrations.AlterField(
            model_name='charged_car',
            name='insurance_ban_expire',
            field=models.DateField(blank=True, default=datetime.date(2022, 5, 15), null=True),
        ),
        migrations.AlterField(
            model_name='charged_car',
            name='tax_ban_expire',
            field=models.DateField(blank=True, default=datetime.date(2022, 5, 15), null=True),
        ),
    ]
