# Generated by Django 4.0.2 on 2022-05-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_plate', '0016_alter_captured_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charged_car',
            name='control_ban_expire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charged_car',
            name='insurance_ban_expire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charged_car',
            name='tax_ban_expire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
