# Generated by Django 4.0.2 on 2022-06-01 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_plate', '0017_alter_charged_car_control_ban_expire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police_request',
            name='police',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
