# Generated by Django 4.0.2 on 2022-06-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_plate', '0018_alter_police_request_police'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_charges', models.PositiveIntegerField()),
                ('control_charges', models.PositiveIntegerField()),
                ('tax_charges', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Money charges',
            },
        ),
    ]
