# Generated by Django 4.0.2 on 2022-06-06 10:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('car_plate', '0019_moneycharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_registration',
            name='phone_number_assign',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
