# Generated by Django 4.0.2 on 2022-06-05 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_plate', '0019_moneycharges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_payment', models.PositiveIntegerField(blank=True, null=True)),
                ('tax_payment', models.PositiveIntegerField(blank=True, null=True)),
                ('control_payment', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_plate.car_registration')),
            ],
            options={
                'verbose_name_plural': 'Payment completed',
                'ordering': ['date'],
            },
        ),
    ]
