# Generated by Django 4.0.2 on 2022-04-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_police',
            field=models.BooleanField(default=False),
        ),
    ]
