# Generated by Django 4.0.2 on 2022-05-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_reset_password_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_two_f_enable',
            field=models.BooleanField(default=False),
        ),
    ]
